[[project]]
name = "gateau"
summary = "Retrieving your browser's cookies will be a piece of cake!"
desc = """
gateau is a command line tool which imports your cookies from browsers 
for your curl, wget and httpie requests.
"""
techs = ["Rust", "SQLite", "Firefox", "Chromium"]
links = [{ name = "GitHub", url = "https://github.com/musikid/gateau" }]

[[project]]
name = "pjdfstest.rs"
# img = "https://github.com/musikid/pjdfstest/raw/main/assets/logo.svg?raw=true"
summary = "Rewrite of the pjdfstest suite in Rust."
desc = """
The pjdfstest suite is a test suite for POSIX file systems.
It is used by the FreeBSD
project to test file systems like UFS or ZFS. 
For the 
[Google Summer of Code 2022](https://summerofcode.withgoogle.com/programs/2022/projects/6XPYWLzJ), 
my project was to rewrite the test suite in Rust,
with the goal of improving various aspects of it,
like its performance or configurability,
which are better explained in the [blog post](/blog/rewrite-pjdfstest).
"""
techs = ["Rust", "FreeBSD", "GSoC 2022"]
links = [
	{ name = "Blog post", url = "/blog/rewrite-pjdfstest" },
	{ name = "GitHub", url = "https://github.com/musikid/pjdfstest" },
	{ name = "Book", url = "https://musikid.github.io/pjdfstest" },
]

[[project]]
name = "chwitter"
img = "https://github.com/musikid/chwitter/raw/main/assets/logo.svg?raw=true"
summary = "Twitter, but it's lame."
desc = """
A website similar to Twitter, with fewer functionalities.
The implemented features are messages liking, search function,
friends management, light/dark mode, messages creation and profile editing.
"""
techs = ["HTML", "CSS", "TypeScript", "React", "Node.js", "Express", "MongoDB"]
links = [
	{ name = "GitHub", url = "https://github.com/musikid/chwitter" },
	{ name = "Live instance", url = "https://musikid.github.io/chwitter" },
]

[[project]]
name = "acpi_ec"
img = ""
summary = "Get access to the Embedded Controller (EC) of your laptop."
desc = """
A simple kernel module which takes most of its code from `ec_sys.c`
and provides an interface between the ACPI embedded controller and the userspace.
Its original intent was to be used with NoteBook Fan Control and Fancy.
You can access to the EC simply by read/write to `/dev/ec`.
"""
techs = ["C", "Linux", "Kernel module"]
links = [{ name = "GitHub", url = "https://github.com/musikid/acpi_ec" }]

[[project]]
name = "Fancy"
img = "https://github.com/musikid/fancy/blob/develop/assets/logo.svg?raw=true"
summary = "Control your laptop fans with a fancy software."
desc = """
Fancy is a software which allows controlling laptop fans.
It includes a service daemon to allow accessing to the EC
and controlling it through D-Bus, 
a CLI to send commands and a GUI (WIP).
"""
techs = ["Rust", "D-Bus"]
links = [
	{ name = "GitHub", url = "https://github.com/musikid/fancy" },
	{ name = "Book", url = "https://musikid.github.io/fancy" },
]
